global using QrLinkki.Application.DTOS;
global using QrLinkki.Domain.Entities;
global using QrLinkki.Application.DTOS.Mappers;
global using QrLinkki.Application.Interfaces;
global using QrLinkki.Application.Services;
global using QrLinkki.Api.Extensions;
global using QrLinkki.Api.Endpoints;
global using QrLinkki.Infrastructure.Persistence;
global using Microsoft.EntityFrameworkCore;
